# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hooksy < Formula
  desc "Claude Code Security Inspector - A security gateway for Claude Code hooks"
  homepage "https://github.com/ihavespoons/hooksy"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.7.0/hooksy_0.7.0_darwin_amd64.tar.gz"
      sha256 "a6bc7d5cce31ea35a9b2740902810ad4c15d4282f6c8a035ddc820b373cc4b9b"

      def install
        bin.install "hooksy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.7.0/hooksy_0.7.0_darwin_arm64.tar.gz"
      sha256 "bbc27918c86076865a6805c6ab5fb4618a9141bba63bd56e7c62cbd5e6f2ae14"

      def install
        bin.install "hooksy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.7.0/hooksy_0.7.0_linux_amd64.tar.gz"
      sha256 "f4884d08e2b7bf13f7c564d59a4558156084ba9983b33fb9d79b0688938ba867"
      def install
        bin.install "hooksy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.7.0/hooksy_0.7.0_linux_arm64.tar.gz"
      sha256 "ea7493f8f2fac47faa191a9bc2cbb199745dc5a782ee9d89f0dc612c1c4e96ca"
      def install
        bin.install "hooksy"
      end
    end
  end

  test do
    system "#{bin}/hooksy", "--version"
  end
end
