# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hooksy < Formula
  desc "Claude Code Security Inspector - A security gateway for Claude Code hooks"
  homepage "https://github.com/ihavespoons/hooksy"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.3.0/hooksy_0.3.0_darwin_amd64.tar.gz"
      sha256 "58d1d34a36974ad2f9b079c3fc5c22cde8ecaf1d9b5abd00dc1dbba6e0520c93"

      def install
        bin.install "hooksy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.3.0/hooksy_0.3.0_darwin_arm64.tar.gz"
      sha256 "2d4541653c2adfa96a6e855e1ae3b9a2107d4f5df5576bc0d478b22fa7861ca9"

      def install
        bin.install "hooksy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.3.0/hooksy_0.3.0_linux_amd64.tar.gz"
      sha256 "633aed5aa824d800fcdabaf1b57d4bfae30f34c1d97289e7c32727b4930c24c8"
      def install
        bin.install "hooksy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.3.0/hooksy_0.3.0_linux_arm64.tar.gz"
      sha256 "7761fb3f64cd63fba1bca416844a7157a17d4afb063df5dda905c5c57321f18f"
      def install
        bin.install "hooksy"
      end
    end
  end

  test do
    system "#{bin}/hooksy", "--version"
  end
end
