# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hooksy < Formula
  desc "Claude Code Security Inspector - A security gateway for Claude Code hooks"
  homepage "https://github.com/ihavespoons/hooksy"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.6.0/hooksy_0.6.0_darwin_amd64.tar.gz"
      sha256 "458c0737d721b1e7476fdb469a3960429f3501b1e6e602d80400214520582bf3"

      def install
        bin.install "hooksy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.6.0/hooksy_0.6.0_darwin_arm64.tar.gz"
      sha256 "b08ebc027280601175258c4efa30e6f24757e8cdd7080cf0ba47c8dd20fed56f"

      def install
        bin.install "hooksy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.6.0/hooksy_0.6.0_linux_amd64.tar.gz"
      sha256 "7c0a21821b2d7133ab4e6f34993ac797ffd0b18a4275ebd83826b636696765d9"
      def install
        bin.install "hooksy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/hooksy/releases/download/v0.6.0/hooksy_0.6.0_linux_arm64.tar.gz"
      sha256 "efe4b19a139b805a109c716a0c6cfc39be6482275947818d4c5c69caa338a40b"
      def install
        bin.install "hooksy"
      end
    end
  end

  test do
    system "#{bin}/hooksy", "--version"
  end
end
