# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quokka < Formula
  desc "LLM-assisted code review tool with agent orchestration"
  homepage "https://github.com/diffsec/quokka"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/diffsec/quokka/releases/download/v0.9.0/quokka_0.9.0_darwin_amd64.tar.gz"
      sha256 "462043616147101e03730a4609dd5ab333750740f16bc6737b91054bd2646f8a"

      define_method(:install) do
        bin.install "quokka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/diffsec/quokka/releases/download/v0.9.0/quokka_0.9.0_darwin_arm64.tar.gz"
      sha256 "571e421f742eb556d694fe1f2a336c1368ded0c0424865214b1b1b86f3a8c3df"

      define_method(:install) do
        bin.install "quokka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/diffsec/quokka/releases/download/v0.9.0/quokka_0.9.0_linux_amd64.tar.gz"
      sha256 "270e6663a8c803323feac8d8dd9f28ddfcedb394b47e46d47c6f93ae39315305"
      define_method(:install) do
        bin.install "quokka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/diffsec/quokka/releases/download/v0.9.0/quokka_0.9.0_linux_arm64.tar.gz"
      sha256 "5582e231d3bfc09ca61bd23635d5fd0648cac1d2298dc2356bb16c9ae436850b"
      define_method(:install) do
        bin.install "quokka"
      end
    end
  end

  test do
    system "#{bin}/quokka", "--version"
  end
end
