# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reorg < Formula
  desc "Personal organization tool for managing areas, projects, and tasks"
  homepage "https://github.com/ihavespoons/reorg"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/reorg/releases/download/v0.0.7/reorg_0.0.7_darwin_amd64.tar.gz"
      sha256 "5edd7fb4d30b41c2afacb05bb345119b903d9e94aad60d113c3608de3fcfdc3f"

      def install
        bin.install "reorg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/reorg/releases/download/v0.0.7/reorg_0.0.7_darwin_arm64.tar.gz"
      sha256 "eff75b281df2d8679fc06a1ba70816244396687b8447f8279844dcce4dc6ef15"

      def install
        bin.install "reorg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/reorg/releases/download/v0.0.7/reorg_0.0.7_linux_amd64.tar.gz"
      sha256 "b32a86d11e7c25330917a592e5476d485331f0d631d5ab21b205912516d2100e"
      def install
        bin.install "reorg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/reorg/releases/download/v0.0.7/reorg_0.0.7_linux_arm64.tar.gz"
      sha256 "4bd212ca0a898b07e78420903897719a9fb9a0537773339434b082fda0484144"
      def install
        bin.install "reorg"
      end
    end
  end

  test do
    system "#{bin}/reorg", "--help"
  end
end
