# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synq < Formula
  desc "Sync configuration files across machines via GitHub"
  homepage "https://github.com/ihavespoons/synq"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/synq/releases/download/v0.1.0/synq_0.1.0_darwin_amd64.tar.gz"
      sha256 "e1e33d254a4daac9fc652f80f72bcedfe3b8aca54ef50c5ff9d5fe8a8f41d6c4"

      def install
        bin.install "synq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/synq/releases/download/v0.1.0/synq_0.1.0_darwin_arm64.tar.gz"
      sha256 "6163985e5ebc42f3e112a444bbd309d49ce56b559f74826954ee774de5b6a761"

      def install
        bin.install "synq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/synq/releases/download/v0.1.0/synq_0.1.0_linux_amd64.tar.gz"
      sha256 "c265f1e66981623e4d86d3523131215cd034f2782b4593d5707a6da27c50a612"
      def install
        bin.install "synq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/synq/releases/download/v0.1.0/synq_0.1.0_linux_arm64.tar.gz"
      sha256 "44469b15b75ef03057c38e237763c83b70b5a37d6c45891c5b6ba73233024057"
      def install
        bin.install "synq"
      end
    end
  end

  def caveats
    <<~EOS
      To get started:
        synq setup

      To start the background sync daemon:
        brew services start synq

      To stop the daemon:
        brew services stop synq
    EOS
  end

  service do
    run [opt_bin/"synq", "daemon", "start", "--foreground"]
    keep_alive true
    log_path var/"log/synq/synq.log"
    error_log_path var/"log/synq/synq.err"
    working_dir var
  end

  test do
    system "#{bin}/synq", "--version"
  end
end
