# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tau < Formula
  desc "Coding agent for your terminal — a Go reimplementation of Pi"
  homepage "https://github.com/ihavespoons/tau"
  version "0.21.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/tau/releases/download/v0.21.1/tau_0.21.1_darwin_amd64.tar.gz"
      sha256 "f5158da5f6149ce6120d4d69a923d9784b5006557cabbebd36500fc45db7b86f"

      define_method(:install) do
        bin.install "tau"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/tau/releases/download/v0.21.1/tau_0.21.1_darwin_arm64.tar.gz"
      sha256 "04655dbdb8d5f1e2d7e3e16bbdefd9805f8459faa2f30b5ec0c7618ae9ab039c"

      define_method(:install) do
        bin.install "tau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/tau/releases/download/v0.21.1/tau_0.21.1_linux_amd64.tar.gz"
      sha256 "996b9c11593b8a31bfb884adb3670ec34d37ddca9dd3e0a3de1205ea2b9727ff"
      define_method(:install) do
        bin.install "tau"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/tau/releases/download/v0.21.1/tau_0.21.1_linux_arm64.tar.gz"
      sha256 "ab549c267b97e275310871d417deec9e00f4dc6cc180d87ba1316ce084edd82c"
      define_method(:install) do
        bin.install "tau"
      end
    end
  end

  test do
    system "#{bin}/tau --version"
  end
end
