# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tau < Formula
  desc "Coding agent for your terminal — a Go reimplementation of Pi"
  homepage "https://github.com/ihavespoons/tau"
  version "0.34.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/tau/releases/download/v0.34.0/tau_0.34.0_darwin_amd64.tar.gz"
      sha256 "25cc0011552939ac4d673765515222111d3d34be800640f57db599631ca11eed"

      define_method(:install) do
        bin.install "tau"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/tau/releases/download/v0.34.0/tau_0.34.0_darwin_arm64.tar.gz"
      sha256 "bda1e6bcb4e86550c3fff13017c342395fb08332b9b101efe6be01715f8cda5e"

      define_method(:install) do
        bin.install "tau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/tau/releases/download/v0.34.0/tau_0.34.0_linux_amd64.tar.gz"
      sha256 "19f0eb1d5c02e1f71bd9e95a147e5f6a17c5edef8666dd257a3b9cdca38e256c"
      define_method(:install) do
        bin.install "tau"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/tau/releases/download/v0.34.0/tau_0.34.0_linux_arm64.tar.gz"
      sha256 "956dadc8f617254066b11594b7b44ebacdb7c2774406acfe1e9e822f73c6a5b7"
      define_method(:install) do
        bin.install "tau"
      end
    end
  end

  test do
    system "#{bin}/tau --version"
  end
end
