# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tau < Formula
  desc "Coding agent for your terminal — a Go reimplementation of Pi"
  homepage "https://github.com/ihavespoons/tau"
  version "0.30.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/tau/releases/download/v0.30.0/tau_0.30.0_darwin_amd64.tar.gz"
      sha256 "2cde8babedaeba9bd01266483d7144afa6b548ce2ed91f371e1b670fea83a448"

      define_method(:install) do
        bin.install "tau"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/tau/releases/download/v0.30.0/tau_0.30.0_darwin_arm64.tar.gz"
      sha256 "5c762eea52e17069d13a3f52ad1d87039e070e6abf7fe393014918864c9e3d69"

      define_method(:install) do
        bin.install "tau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/tau/releases/download/v0.30.0/tau_0.30.0_linux_amd64.tar.gz"
      sha256 "fcf9d34700aaaee034babea738d872dedf59f8b988ffecb8198680624a0e5d09"
      define_method(:install) do
        bin.install "tau"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/tau/releases/download/v0.30.0/tau_0.30.0_linux_arm64.tar.gz"
      sha256 "3d0b3d5bcd5f8701159e4f91ab707fea5834771f05402cb01ffbd319d8abbf74"
      define_method(:install) do
        bin.install "tau"
      end
    end
  end

  test do
    system "#{bin}/tau --version"
  end
end
