# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zrok < Formula
  desc "LLM-assisted code review tool with agent orchestration"
  homepage "https://github.com/ihavespoons/zrok"
  version "0.2.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/zrok/releases/download/v0.2.5/zrok_0.2.5_darwin_amd64.tar.gz"
      sha256 "b4a724867de873a300bc9f5abb8fbbd57c44012f8fcef63e90a1d283cdc101fa"

      def install
        bin.install "zrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/zrok/releases/download/v0.2.5/zrok_0.2.5_darwin_arm64.tar.gz"
      sha256 "d3034be0bb0d6806e3c6a8cead5467aa6b2731ec12250ca99dd36bfef47c7526"

      def install
        bin.install "zrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/zrok/releases/download/v0.2.5/zrok_0.2.5_linux_amd64.tar.gz"
      sha256 "4cb1c7dac14aeedb4a01cc846ac557c4807ff31a793cbf15fc4d88ee7280a43d"
      def install
        bin.install "zrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/zrok/releases/download/v0.2.5/zrok_0.2.5_linux_arm64.tar.gz"
      sha256 "401c8abc79be0bbee8b1b761103ce83f5d5d6f31c880c7004f1d5febbbc0972d"
      def install
        bin.install "zrok"
      end
    end
  end

  test do
    system "#{bin}/zrok", "--version"
  end
end
