# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zrok < Formula
  desc "LLM-assisted code review tool with agent orchestration"
  homepage "https://github.com/ihavespoons/zrok"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ihavespoons/zrok/releases/download/v0.3.0/zrok_0.3.0_darwin_amd64.tar.gz"
      sha256 "b4dca78e51cf02a72f8c407ae075e579153bb29f107ebaeb246aa739bea0f4fc"

      def install
        bin.install "zrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ihavespoons/zrok/releases/download/v0.3.0/zrok_0.3.0_darwin_arm64.tar.gz"
      sha256 "0315d4a682076f1965dc2bcce3a93eb6c1f845d6ad81ad04c24d01a40b6de741"

      def install
        bin.install "zrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/zrok/releases/download/v0.3.0/zrok_0.3.0_linux_amd64.tar.gz"
      sha256 "f9a95c8b0adaf5ac1169d1e189b06660320e091bea29e6f1794179433656ca69"
      def install
        bin.install "zrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ihavespoons/zrok/releases/download/v0.3.0/zrok_0.3.0_linux_arm64.tar.gz"
      sha256 "d74c1062c268fa6bdb180c9ea30d81b6d646cdd8059ca9a9cd30146fca04d638"
      def install
        bin.install "zrok"
      end
    end
  end

  test do
    system "#{bin}/zrok", "--version"
  end
end
